### ISSUE TITLE
Un-styled background on mobile

### ISSUE THREAD

**Issue by OkkarMin** [OkkarMin/where-to-mug#17]
@dannyyys Could you please check with your mobile if you too see the following 'extra' unstyled background

![IMG_C3510E71DB51-1](https://user-images.githubusercontent.com/24297303/124377652-91fc9780-dcdf-11eb-9dd3-b4bf32041ccf.jpeg)

**Comment by dannyyys** [comment]
No issue on galaxy s9+.
![Screenshot_20210704-162551_Chrome](https://user-images.githubusercontent.com/70012669/124378552-88c1f980-dce4-11eb-8c3b-27aa95434364.jpg)

**Comment by dannyyys** [comment]
@OkkarMin would you like to fix this instead? I do not own an iPhone to test while im debugging.

**Comment by OkkarMin** [comment]
Okay! I will get on it
