### ISSUE TITLE
Improve performance when displaying free room cards

### ISSUE THREAD

**Issue by OkkarMin** [OkkarMin/where-to-mug#2]
Currently, the app is slow to respond to filter

**Comment by OkkarMin** [comment]
@dannyyys Check out the branch https://github.com/OkkarMin/where-to-mug/tree/perf-preventUnnecessaryRerenders

Preview: https://where-to-mug-q2rfojucy-okkar.vercel.app/

Note:
As suggested by @HJunyuan, this branch introduced usage of `React.memo` and `useCallback` to prevent unwanted renders. Taking pointers from [this](https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render) and [this](https://medium.com/hootsuite-engineering/react-re-render-optimization-7d369e0bf701) article

**Comment by dannyyys** [comment]
> @dannyyys Check out the branch https://github.com/OkkarMin/where-to-mug/tree/perf-preventUnnecessaryRerenders
> 
> Preview: https://where-to-mug-q2rfojucy-okkar.vercel.app/
> 
> Note:
> As suggested by @HJunyuan, this branch introduced usage of `React.memo` and `useCallback` to prevent unwanted renders. Taking pointers from [this](https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render) and [this](https://medium.com/hootsuite-engineering/react-re-render-optimization-7d369e0bf701) article

LGTM!!
