### ISSUE TITLE
Room card not displaying the right timeslot color

### ISSUE THREAD

**Issue by dannyyys** [OkkarMin/where-to-mug#4]
It seems that this bug only happen on certain devices. 
![timeslot icon bug](https://user-images.githubusercontent.com/70012669/124097949-a7c74e00-da8e-11eb-9a1b-2389243c09d2.jpg)

**Comment by OkkarMin** [comment]
I propose to remove icons totally.

Icons are too similar that it's not much of a help. How do you feel @dannyyys ?

**Comment by dannyyys** [comment]
sounds good!!

**Comment by dannyyys** [comment]
> I propose to remove icons totally.
> 
> Icons are too similar that it's not much of a help. How do you feel @dannyyys ?

sounds good!!

**Comment by OkkarMin** [comment]
Okay I will get on it tomorrow
