### ISSUE TITLE
Update room cluster

### ISSUE THREAD

**Issue by dannyyys** [OkkarMin/where-to-mug#45]
Reclassify CS-TR+8, CS-TR+9 and LRGTVSTUDIO under WKWSCI

**Comment by OkkarMin** [comment]
Refer to : https://www.linkedin.com/feed/update/urn:li:activity:6828322724239196160?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6828322724239196160%2C6832567603693789184%29
